#!/bin/bash
# Terminal Test Script
echo "🚀 Enhanced Terminal Features Test"
echo "===================================="
echo ""
echo "📅 Current Date: $(date)"
echo "👤 Current User: $(whoami)" 
echo "📍 Current Directory: $(pwd)"
echo "🐚 Current Shell: $SHELL"
echo ""
echo "🎨 Testing Color Support:"
echo -e "\033[31mRed Text\033[0m"
echo -e "\033[32mGreen Text\033[0m" 
echo -e "\033[33mYellow Text\033[0m"
echo -e "\033[34mBlue Text\033[0m"
echo ""
echo "📂 Directory Contents (first 5):"
ls -la | head -5
echo ""
echo "🔧 Available Custom Functions:"
echo "- status    : Show project status"
echo "- mkcd      : Create and enter directory"
echo "- extract   : Extract various archive formats"
echo "- glt       : Git log with timestamps"
echo "- weather   : Show weather info"
echo "- myip      : Show external IP"
echo ""
echo "✅ Terminal enhancement test complete!"
